### ISSUE TITLE
Use *

### ISSUE THREAD

**Issue by benschwarz** [jney/grunt-rework#1]
Is there a way to prefix every property that rework deals with? I'd rather not have to list every property that requires vendor prefixes.

**Comment by unphased** [comment]
Wouldn't this be a question for the rework project? At any rate, it does not appear that rework is the _most_ friendly CSS prefixer at this point, [autoprefixer](https://github.com/ai/autoprefixer) which has a grunt plugin is probably the way to go.

**Comment by benschwarz** [comment]
@unphased I've since moved on to autoprefixer myself… but I posed this as a question to just know if it was possible.  No response :(
