### ISSUE TITLE
Works with rework-variables?

### ISSUE THREAD

**Issue by njj** [jney/grunt-rework#15]
I've been trying for an hour or so now to get this plugin to work with variables and can't seem to get anything to work correctly.  Here's my setup.

``` javascript
module.exports = function(grunt) {
    var rework_import = require('rework-import');
    var rework_vars = require('rework-vars');

    grunt.initConfig({
      rework: {
        'dest/index.css': 'src/index.css',
        options: {
          toString: { compress: false },
          use: [
            rework_import,
            rework_vars
          ]
        }
      }
    });

    grunt.loadNpmTasks('grunt-rework');

    grunt.registerTask('default', ['rework']);
}
```

The output is identical to the input.

**Comment by njj** [comment]
Actually after a bit of poking around it appears that media queries are not being converted for some reason, while regular variables are fine.

``` css
@media (min-width: var(--screen-sm-min)) {
  .full-width-section {
    padding-left: 35px;
  }
}
```

Which is a separate issue here: https://github.com/reworkcss/rework-vars/issues/17

**Comment by tszebeni** [comment]
For reference here is a fix:
rework_vars({})

so when declare as use, you need to invoke it with options.
