### ISSUE TITLE
Update to rework 1.0

### ISSUE THREAD

**Issue by lazd** [jney/grunt-rework#8]
https://github.com/reworkcss/rework/releases/tag/1.0.0

**Comment by jney** [comment]
hi @lazd , i'm not using grunt anymore in my new projects, are you interested in taking grunt-rework ownership ?

**Comment by lazd** [comment]
@jney, thanks for the quick merge!

As far as taking over ownership, my plate is quite full, but in the interest of making sure the package is up to date, I can take over ownership and delegate accordingly.
